### ISSUE TITLE
Column not loading as date in pandas.SQLQueryDataset despite setting parse_dates

### ISSUE THREAD

**Issue by galenseilisnh** [kedro-org/kedro-plugins#1016]
## Description

I have this data source in my configuration. Given the `parse_dates` containing a list that contains `ds`, I was expecting that `ds` would be parsed as a datetime. Indeed, I checked that it is actually being loading as `<class 'str'>`.

```yaml
# conf/base/catalog.yml

historical_demand:
  type: pandas.SQLQueryDataset
  credentials:
    con:  <connection_str>
  filepath: scripts/historical_demand.sql
  load_args:
    parse_dates:
      - ds
```

However, when I load the dataset and run `df.info()` I see that the column is actually still just `object`. I want to have this column be loaded as a datetime such that I can put

```python
            "ds": Column(pa.DateTime, nullable=False),
```

in a Pandera schema for validation.

Now, of course, I would just convert the column to datetime format within my nodes. Indeed, I confirmed that this would work. So I am not blocked on working on this, but `load_args` did not produce the result I had expected. 

The upstream sql query has `CONVERT(date, Foo_Date) AS ds` which does not give any error. Inspection of a couple of hundred rows isn't showing anything that doesn't look like a date either.

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
1. Init a project.
2. Construct catalog as above.
3. Check data type of 'ds' column.

## Expected Result

Chosen column should be loaded as a date time format.

## Actual Result

Still treated as "object".

When validating with the aforementioned Pandera schema, I get this error.

```python
SchemaError: expected series 'ds' to have type datetime64[ns], got object
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

- kedro, version 0.19.11
- No plugins other than kedro-viz, but that should have no effect here.
- Python 3.10.4
- OS Windows
