### ISSUE TITLE
CSVDataset compression issue

### ISSUE THREAD

**Issue by ReyJust** [kedro-org/kedro-plugins#1028]
## Description
I started getting an issues while saving a CSV dataset using compression.
The error:
```
[03/05/25 10:00:00] WARNING  <string>:2: RuntimeWarning: compression has no effect when passing a non-binary object as input.                      warnings.py:110
```
Actually, it's just a warning, but compression was not taken.
Furthermore, in my actual project, I was uploading to AWS S3, with `ContentEncoding` as `gzip`. It then create an error while trying to download it from the web UI. The file became irretrievable! 😢 

Here's my catalog config:
```yaml
{filename}.processed:
  type: pandas.CSVDataset
  versioned: False
  filepath: "${PATH}"
  save_args:
    index: False
    compression:
      method: gzip
      compresslevel: 9
  load_args:
    compression: gzip
```

For it to work, I had to append theses:
```yaml
  [...]
  fs_args:
    open_args_save:
      mode: wb
```

I just wanted to make sure that expected behavior!

Thanks, Justin
