### ISSUE TITLE
`HFDataset` has no attribute `_version`

### ISSUE THREAD

**Issue by ianwhale** [kedro-org/kedro-plugins#1081]
## Description

Small issue with the `HFDataset`. It seems to be out of date with some API change for `AbstractVersionedDataset`.

## Context

Load data from Hugging Face.

## Steps to Reproduce

YAML entry (not important to reproduce):

```yaml
raw_meta_CDs_and_Vinyl:
  type: sequential_transformer.datasets.HFDataset
  dataset_name: McAuley-Lab/Amazon-Reviews-2023
  dataset_kwargs:
    name: raw_meta_CDs_and_Vinyl
    trust_remote_code: true
```

Then, in `ipython`:

```python
catalog.load("raw_meta_CDs_and_Vinyl")
```

## Expected Result

Dataset should be loaded from HF `load_dataset` function.

## Actual Result

```
AttributeError: 'HFDataset' object has no attribute '_version'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): `Version: 0.19.12`
* Kedro plugin and kedro plugin version used (`pip show kedro-datasets`): `Version: 7.0.0`
* Python version used (`python -V`): `Python 3.11.9`
* Operating system and version: `macOS Sequoia 15.5`.

## Suggested fix

Just need to extend `AbstractDataset` instead of `AbstractVersionedDataset`.

You can't save this dataset anyway, so there's no real issue with this quick change.

Unless... #1058.
