### ISSUE TITLE
`kedro-airflow` does not combine nodes of `MemoryDataset` defined in the catalog

### ISSUE THREAD

**Issue by boukepostma** [kedro-org/kedro-plugins#1085]
## Description
kedro-airflow does not combine nodes of Memorydataset with copy_mode: assign after running
`kedro airflow create` with the `--group-in-memory` flag

## Context
I want to use kedro to author simulations workflow where I am working with objects that can't be fully serialized between nodes. As the objects are quite large, I would like to use MemoryDataset with `copy_mode: assign`.

## Steps to Reproduce
1. `kedro new -e y --tools none --name reproduce_bug`
2. Run `kedro airflow create --target-dir=dags/ --group-in-memory`
3. Inspect how DAG looks like 
4. In the data catalog, change `X_train` and `y_train` from the default `MemoryDataset` to one with `copy_mode: assign`: 
```yaml
X_train:
   type: MemoryDataset
   copy_mode: assign

y_train:
   type: MemoryDataset
   copy_mode: assign
``` 
5. Observe that new tasks appeared 

## Expected Result
I would expect exactly thesame DAG regardless of copy_mode.

## Actual Result
More tasks appear in the DAG.

## Your Environment
* Kedro version used (`pip show kedro` or `kedro -V`): 0.19.12
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`): kedro-airflow=0.9.2
* Python version used (`python -V`): 3.12
* Operating system and version: Windows

**Comment by merelcht** [comment]
Hi @boukepostma, thanks for flagging this! I tried to replicate the issue and it looks like this happens when you add a dataset in the catalog regardless of whether you add the copy_mode or not. So even just adding:

```yaml
X_train:
  type: MemoryDataset

y_train:
  type: MemoryDataset
```

Will result in added tasks in the DAG. I'm adding this to our backlog.
