### ISSUE TITLE
Cannot specify dtypes with `polars.CSVDataSet`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#124]
## Description
As per title.

## Context
I was trying to load a problematic CSV file, which loads just fine when calling `pl.read_csv` manually:

```python
df = pl.read_csv(
    "../data/01_raw/OpenRepairData_v0.3_aggregate_202210.csv",
    dtypes={
        "product_age": pl.Float64,
        "group_identifier": pl.Utf8,
    },
    parse_dates=True,
)
```

However, when turning that to a catalog entry:

```yaml
openrepair-0_3-events-raw:
  type: polars.CSVDataSet
  filepath: data/01_raw/OpenRepairData_v0.3_aggregate_202210.csv
  load_args:
    dtypes:
      product_age: pl.Float64
      group_identifier: pl.Utf8
    parse_dates: true
```

I get an error, because it's treating the dypes as strings and instead Polars dtypes are needed:

```
...
DataSetError: Failed while loading data from data set CSVDataSet(filepath=/Users/juan_cano/Projects/QuantumBlack 
Labs/talk-kedro-polars/data/01_raw/OpenRepairData_v0.3_aggregate_202210.csv, load_args={'dtypes': 
{'group_identifier': pl.Utf8, 'product_age': pl.Float64}, 'parse_dates': True, 'rechunk': True}, protocol=file, 
save_args={}).
Cannot infer dtype from 'pl.Float64' (type: str)
```

Unfortunately I don't think Polars supports any other way of passing the dtypes, so I'm not sure if there's a workaround.

More broadly speaking, I guess my problem is that I don't know how to specify non-primitive types in a catalog entry.

## Steps to Reproduce
See above

## Expected Result
I should be able to specify dtypes for polars datasets.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): `kedro, version 0.18.6`
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`): I'm stalling kedro-starters with `pip install kedro-datasets[pandas.CSVDataSet,polars.CSVDataSet] @ git+https://github.com/wmoreiraa/kedro-plugins@4448b9f#subdirectory=kedro-datasets`, hence from https://github.com/wmoreiraa/kedro-plugins@4448b9f
* Python version used (`python -V`): 3.10.9
* Operating system and version: macOS Ventura

**Comment by astrojuanlu** [comment]
As a workaround, @marrrcin suggested this trick:

```python
# settings.py
from kedro.config import TemplatedConfigLoader

import polars as pl

CONFIG_LOADER_CLASS = TemplatedConfigLoader
CONFIG_LOADER_ARGS = {
    "globals_dict": {
        "pl_Float64": pl.Float64,
        "pl_Utf8": pl.Utf8,
    },
}
```

```yaml
# catalog.yml
openrepair-0_3-events-raw:
  type: polars.CSVDataSet
  filepath: data/01_raw/OpenRepairData_v0.3_aggregate_202210.csv
  load_args:
    dtypes:
      product_age: ${pl_Float64}
      group_identifier: ${pl_Utf8}
    try_parse_dates: true
```

and it works beautifully ✨ but going forward, @datajoely has suggested we should have an OmegaConf-based solution.
