### ISSUE TITLE
Cannot use `file_format: delta` with `polars.EagerPolarsDataset`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#444]
## Description
As per title.

I think the reason is that, annoyingly, not all `pl.DataFrame.write_*` methods are equivalent: some can take a buffer, but some others can't.

Compare these two:
- https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_parquet.html
- https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_delta.html

## Steps to Reproduce
```yaml
statuses_table:
  type: polars.EagerPolarsDataset
  file_format: delta
  filepath: s3://social-summarizer/statuses
  save_args:
    storage_options:
      AWS_ENDPOINT_URL: "http://127.0.0.1:9010"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY": "minioadmin"
      AWS_REGION: "<localhost>"
      AWS_ALLOW_HTTP: "true"
      AWS_S3_ALLOW_UNSAFE_RENAME: "true"
```

## Expected Result
The dataset gets written.

## Actual Result
```
File ~/.micromamba/envs/kedrohf311-talk/lib/python3.11/site-packages/deltalake/writer.py:441, in try_get_table_and_table_uri(table_or_uri, storage_options)
    440 if not isinstance(table_or_uri, (str, Path, DeltaTable)):
--> 441     raise ValueError("table_or_uri must be a str, Path or DeltaTable")
    443 if isinstance(table_or_uri, (str, Path)):

ValueError: table_or_uri must be a str, Path or DeltaTable
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.14
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`): 2.15.0
* Python version used (`python -V`): 3.11
* Operating system and version: macOS Ventura
