### ISSUE TITLE
Problems defining a PartitionedDataset in the Data Catalog

### ISSUE THREAD

**Issue by cpinon-grd** [kedro-org/kedro-plugins#501]
## Description

I'm encountering a problem when trying to define a `PartitionedDataset` in the `catalog.yml`for a Kedro project. Despite following the documentation, I receive an error when listing the catalog or trying to use it in a node.

## Context
This bug is hindering my data pipeline development. I'm trying to set up a partitioned dataset to manage large volumes of session data files efficiently.

## Steps to Reproduce
1. Define a PartitionedDataset in the catalog.yml as follows:

```
sessions_raw_set:
  type: PartitionedDataset
  path: data/01_raw/sessions
  dataset: 
    type: polars.CSVDataset
    load_args:
      new_columns: ["ID","IP_GGSN", "APN", "IP_Radius_Client", "IP_Device", "sbytes", "dbytes","spkts","dpkts", "dur","SessionState","Timestamp"]
      has_header: false
      ignore_errors: True
    filename_suffix: '.csv'
```
The dataset `load_args` are most likely correct, since I have used them to load single csv files without any error like this:

```
sessions_raw:
   type: polars.CSVDataset
   filepath: data/01_raw/sessions.csv
   load_args:
     new_columns: ["ID","IP_GGSN", "APN", "IP_Radius_Client", "IP_Device",
             "sbytes", "dbytes","spkts","dpkts", "dur","SessionState","Timestamp"]
     has_header: false
     ignore_errors: True
```

2. Run `kedro catalog list` or try to use the dataset in a node.

## Expected Result
The `PartitionedDataset` should be recognized, listed in the catalog, and usable in nodes without errors.

## Actual Result
When I run kedro catalog list or try to use the dataset in a node, I get the following error:

```
Traceback (most recent call last):
  File "/home/cpinon/Documentos/SecBluRed/SourceCode/secblured/.venv/lib/python3.9/site-packages/kedro/io/core.py", line 145, in from_config
    class_obj, config = parse_dataset_definition(
  File "/home/cpinon/Documentos/SecBluRed/SourceCode/secblured/.venv/lib/python3.9/site-packages/kedro/io/core.py", line 396, in parse_dataset_definition
    raise DatasetError(f"Class '{dataset_type}' not found, is this a typo?")
kedro.io.core.DatasetError: Class 'PartitionedDataset' not found, is this a typo?

```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.19.1
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`): kedro-datasets version 2.0.0
* Python version used (`python -V`): 3.9.18
* Operating system and version: Ubuntu 20.04

Thanks for your time in advance!

**Comment by merelcht** [comment]
Hi @cpinon-grd, thanks for flagging this issue. I think the problem might be that you need to specify the type as `partitions.PartitionedDataset`, so your catalog entry would become: 
```yml
sessions_raw_set:
  type: partitions.PartitionedDataset
  path: data/01_raw/sessions
  dataset:
    type: polars.CSVDataset
    load_args:
      new_columns: ["ID","IP_GGSN", "APN", "IP_Radius_Client", "IP_Device", "sbytes", "dbytes","spkts","dpkts", "dur","SessionState","Timestamp"]
      has_header: false
      ignore_errors: True
    filename_suffix: '.csv'
``` 

We moved the `PartitionedDataset` from the core Kedro package to `kedro-datasets`, so I think some importing logic has changed here. Let me know whether this works and I'll update the docs accordingly.
