### ISSUE TITLE
EagerPolarsDataset returning codec issue

### ISSUE THREAD

**Issue by Dekermanjian** [kedro-org/kedro-plugins#551]
## Description
EagerPolarsDataset returning codec issue. However reading the same parquet file with `pl.read_parquet()` works

## Context
I can not use polars to read the data

## Steps to Reproduce
My catalog.yml looks like this:
```
Billed_denials:
  type: polars.EagerPolarsDataset
  filepath: data/02_intermediate/Billed_denials.parquet
  file_format: parquet
```

## Expected Result
To load the parquet file with polars

## Actual Result

-- If you received an error, place it here.
```
DatasetError: Failed while loading data from data set EagerPolarsDataset(file_format=parquet, 
filepath=data/02_intermediate/Billed_denials.parquet, load_args={}, 
protocol=file, save_args={}).
'utf-8' codec can't decode byte 0xc0 in position 1: invalid start byte
```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 19.2
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`): 2.0.0
* Python version used (`python -V`): 3.10.13
* Operating system and version: Linux and Windows
