### ISSUE TITLE
SparkJDBCDataset not working when specify a query instead of a table

### ISSUE THREAD

**Issue by DavidRetana-TomTom** [kedro-org/kedro-plugins#639]
## Description
When using SparkJDBCDataset you need to specify table name as a mandatory parameter. However, using the spark JDBC connector directly, you can specify a query to retrieve data from the database instead of hardcoding a single table. Check out [this](https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html) link.
According to the official Spark documentation:

The specified query will be parenthesized and used as a subquery in the FROM clause.
Below are a couple of restrictions while using this option.
1. It is not allowed to specify dbtable and query options at the same time.
2. It is not allowed to specify query and partitionColumn options at the same time. When specifying partitionColumn option is required, the subquery can be specified using dbtable option instead and partition columns can be qualified using the subquery alias provided as part of dbtable.
Example:
spark.read.format("jdbc")
.option("url", jdbcUrl)
.option("query", "select c1, c2 from t1")
.load()

## Context
This is specially important if you want to read data from multiple tables in the database or if you want to run complex or spatial queries in the database instead of retrieving all the data and perform the computations in the cluster.

## Steps to Reproduce
Source code right now:
```python
if not table:
    raise DatasetError(
        "'table' argument cannot be empty. Please "
        "provide the name of the table to load or save "
        "data to."
    )
```

## Expected Result
I would like to have something like the following:
```yaml
weather:
  type: spark.SparkJDBCDataSet
  query: SELECT field1, field2 FROM weather_table WHERE <condition>
  url: jdbc:postgresql://localhost/test
  credentials: db_credentials
  load_args:
    properties:
      driver: org.postgresql.Driver
  save_args:
    properties:
      driver: org.postgresql.Driver
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.19.3
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`):
* Python version used (`python -V`): 3.10
* Operating system and version: aarch64 GNU/Linux
