### ISSUE TITLE
Problem creation a partitions.PartitionedDataSet

### ISSUE THREAD

**Issue by Premji98** [kedro-org/kedro-plugins#679]
## Description
I am using kedro (version 0.19.5) 

I am trying to create this dataset on top of ImageDataSet provided in the official documentation.
This gives me error saying "Class 'partitions.PartitionedDataset' not found, is this a typo?"
## Context

I am trying to build a PartitionedDataSet of Images(png). I followed the official documentation on 'pikachu' dataset.

## Steps to Reproduce
1. 
```
dataset_raw:
  type: partitions.PartitionedDataset
  path: data/01_raw  # path to the location of partitions
  dataset: cct_kedro.datasets.image_dataset.ImageDataset  # shorthand notation for the dataset which will handle individual 
  filename_suffix: ".png"
```

## Expected Result
pipeline should run normally
## Actual Result
DatasetError
```
![image](https://github.com/kedro-org/kedro-plugins/assets/145099321/1fc76060-0ff1-4124-9ea0-80b7397e0395)
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:
virtual env with python 3.12

* Kedro version used (`pip show kedro` or `kedro -V`): 0.19.5
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`):
* Python version used (`python -V`):3.12
* Operating system and version:macOS
