### ISSUE TITLE
Misleading `Table not found` error when using wrong database

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#725]
## Description
Today I was playing with the `ibis.TableDataset`, made a mistake in the database path, and found this error:

```
IbisError: Table not found: 'flights'
```

it turns out that it was the database that was wrong, so I fixed a typo in the `connection` section and problem solved.

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
```yaml
# catalog.yml
flights:
  type: ibis.TableDataset
  table_name: flights
  connection:
    backend: duckdb
    database: "non_existent.ddb"
```

## Expected Result
Maybe `non_existent.dbb file not found`?

I guess that the error is being raised by DuckDB trying to create a database file on the fly, and of course finding it empty, hence the error. So not sure how easy this is to fix, or if there would be any unintended side effects.

cc @deepyaman 

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
* Kedro plugin and kedro plugin version used (`pip show kedro-airflow`):
* Python version used (`python -V`):
* Operating system and version:
