### ISSUE TITLE
Make layer less verbose

### ISSUE THREAD

**Issue by pascalwhoop** [kedro-org/kedro-plugins#774]
Hi y'all

we recently switched from

```
layer: foo
```

to

```
  metadata:
    kedro-viz:
      layer: 04_features
```

that's super verbose. Can we please get

```
  metadata.kedro-viz.layer: 01_raw
```

? Else the catalog just becomes suuuuper verbose. There must be a way to be yaml compliant when writing catalog yaml no?

**Comment by noklam** [comment]
> There must be a way to be yaml compliant when writing catalog yaml no?

I am happy if this exists, as of the moment the issue hasn't been addressed, see https://github.com/omry/omegaconf/issues/1188

Alternatlively, you can remove some typing with variable interpolation?

```
catalog.yml

_viz_feature_layer:
  kedro-viz:
    layer: 04_features

my_dataset:
  ...
  metadata: ${_viz_feature_layer}
```
?
