### ISSUE TITLE
feat(datasets): support setting Ibis table schemas

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro-plugins#833]
## Description

I want to set the database schema for the Ibis table referenced by the `ibis.TableDataset`.

## Context

From @mark-druffel on Slack:

> Has anyone used ibis.TableDataset with duckdb schemas? If I set a schema on a data catalog entry I get the error `Invalid Input Error: Could not set option "schema" as a global option` .

```yaml
bronze_x:
  type: ibis.TableDataset
  filepath: x.csv
  file_format: csv
  table_name: x
  backend: duckdb
  database: data.duckdb
  schema: bronze
```

I can reproduce this error with vanilla ibis:

```python
con = ibis.duckdb.connect(database="data.duckdb", schema = "bronze")
```

Found a [related question](https://github.com/ibis-project/ibis/issues/8550) on ibis' github, it sounds like duckdb can't set the schema globally so it has to be done in the table functions. Wondering if this would require a change to ibis.TableDataset, and if so, would this pattern work the same with other backends?

## Possible Implementation

> Wondering if this would require a change to ibis.TableDataset,
If I understand correctly, this would be a request to pass `schema` (actually, `database`, since `schema` is deprecated as an argument to `table`) as a `table_arg` or something in the dataset.

**Comment by deepyaman** [comment]
> and if so, would this pattern work the same with other backends?

I think so, because https://github.com/ibis-project/ibis/blob/main/ibis/backends/sql/__init__.py#L47 for example (called in the table() function) is generic to SQL backends).

**Comment by deepyaman** [comment]
From @mark-druffel:

> Yea I was just looking through some of the other backends, agree. I'm trying to check pyspark now to recall if `table(database)`  is actually equivalent to catalog, database, or schema in hive.
> On the ibis side, it feels like `do_connect` using a database parameter is confusing. For example:
> 
> ```python
> con=ibis.duckdb.connect(database = "data/db/spotify/spotify.duckdb")
> con.create_database(name = "bronze")
> con.create_database(name = "silver")
> con.create_database(name = "gold")
> con.table("x", database = "bronze")
> ```
> 
> The `create_database` & `table` calls use database to mean something completely different.
> On the kedro-datasets side, my question becomes would it make sense to accept an argument called "schema" and just pass that to `table(database = schema)`  since the "database" argument is already used in the connection string for `do_connect`?

I'd be inclined to match the Ibis name, but create a section for `table_args` (i.e. arguments that get passed to the underlying `table()` call), since that's more in line with how most Kedro datasets are structured in my experience, but I haven't thought about it that much.

**Comment by deepyaman** [comment]
> I'd be inclined to match the Ibis name, but create a section for `table_args` (i.e. arguments that get passed to the underlying `table()` call)

Actually, looking at the code, it's more like `load_args` and `save_args`. We already pass `save_args` to `create_table` or `create_view`, which is where you can specify `database="bronze"` (same will hold true for inserts, pending #834). The `table` call is just on `load`, so it makes sense to be `load_args` that we pass there (right now, `load_args` aren't being passed to the `table` call, only the `read_*` call, but I expect `read_*` to move into `FileDataset` after #828).

So this would be very trivial to do. It just seems a bit dumb that you'd pass the schema name twice (to `load_args` and `save_args`), so I guess we can just specify `database` as a top-level key (not under `connection`), and feed them to `load_args`/`save_args` in the `__init__` method.

@mark-druffel curious to know what you think of this approach? This is what it would look like in your example:

```yaml
bronze_x:
  type: ibis.TableDataset
  filepath: x.csv
  file_format: csv
  table_name: x
  connection:  # Nit: Moved the keys under `connection`; assume that was just an oversight in your example
    backend: duckdb
    database: data.duckdb
  database: bronze  # Won't bother with `schema`, to be consistent with Ibis
```

**Comment by mark-druffel** [comment]
@deepyaman Staying consistent with ibis definitely makes sense. I do think the differing `use` of database in do_connect() and table() is confusing, but that's an ibis question/discussion and I'm not sure what parameter names would be better...

**Comment by mark-druffel** [comment]
@deepyaman I've been looking back through this given my pyspark example over slack. I'm still thrown by the duplicative use of `database` as a parameter in Ibis. I've always used language aligned with the image below and find myself getting a bit confused in Ibis because schema is different, but the confluence of database and data frame language makes thing a bit more complicated in Ibis I think 🤷  
![image](https://github.com/user-attachments/assets/79659e42-f1da-41b6-b4ff-3c6d4f9e03ce)
[^Referenced SO Post](https://stackoverflow.com/questions/7022755/whats-the-difference-between-a-catalog-and-a-schema-in-a-relational-database)

Given that, I think using your prior suggestion of `table_args` might be a bit clearer to end users. I could be wrong, but it also feels more akin to FileDataset's `load_args` / `save_args` as you mentioned so I think it would be more natural:
```
# Duckdb
bronze_x:
  type: ibis.TableDataset
  table_name: x
  connection:  
    backend: duckdb
    database: data.duckdb
  table_args:
    database: schema

# Databricks w/ Unity Catalog
bronze_x:
  type: ibis.TableDataset
  table_name: x
  connection:  
    backend: pyspark
    session: session_name #Not sure if this actually works yet, databricks default works with no named session but will test
  table_args:
    database: catalog.schema
```

I'm updating TableDataset and doing some testing on my side, but would love to open a PR if the change makes sense to others?
