### ISSUE TITLE
Polars read schema

### ISSUE THREAD

**Issue by AntonNikishin** [kedro-org/kedro-plugins#884]
## Description
The `schema` and `schema_overrides` arguments cannot be provided as `load_args` for `polars.EagerPolarsDataset`.

## Context
Sometimes, I need to specify the data types when reading a Polars DataFrame. In Python, if I wanted to load a Polars DataFrame with specified column types, I would use: `pl.read_csv("file_name.csv", schema_overrides={"column_name": pl.String})`.

However, when using the Kedro catalog, I cannot specify Polars data types for schema overrides, as Kedro treats them all as strings. Whether I use "str", "String", or "pl.String", they are all interpreted as string arguments for schema overrides, which Polars doesn't recognize.

## Steps to Reproduce
1. Add to catalog the following dataset:
```
dataset_name:
  type: polars.EagerPolarsDataset
  file_format: csv
  filepath: "data/file_name.csv"
  load_args:
    schema_overrides:
      # none of the below works
      'column_name_1': pl.String
      'column_name_2': String
      'column_name_3': str
```
2. Try to load

## Expected Result
Loads Polars DataFrame with desired schema.

## Actual Result
```
DatasetError: Failed while loading data from data set EagerPolarsDataset(file_format=csv, 
filepath=data/file_name.csv, load_args={'schema_overrides': {'column_name': str}}, 
protocol=file, save_args={}).
cannot parse input of type 'str' into Polars data type (given: 'str')
```

## Your Environment
* Kedro version: `0.19.9`
* Kedro datasets version: `5.0.0`
* Python version: 3.10.13
* Operating system and version: MacOS
