### ISSUE TITLE
Polars Datatype Catalog Entry Cannot Partition on Saving Parquet

### ISSUE THREAD

**Issue by alexdavis24** [kedro-org/kedro-plugins#908]
## Description
- I would like to save partitioned Polars parquet datasets which currently relies on Pyarrow using write_parquet
  - Following documentation: [https://docs.pola.rs/api/python/version/0.18/reference/api/polars.DataFrame.write_parquet.html](url)
- When running with default system (Rust-based implementation) or with Pyarrow, Kedro returns errors (see below)
- I have encountered this writing locally and writing to s3 
- Attempting to explicitly pass a `filesystem` within catalog (see code below) does not work.
- I believe this is due to handling as a BytesIO object in the save, rather than a direct write of an expected dataframe:
  - https://docs.kedro.org/projects/kedro-datasets/en/kedro-datasets-4.1.0/_modules/kedro_datasets/polars/lazy_polars_dataset.html#LazyPolarsDataset
  - https://docs.kedro.org/projects/kedro-datasets/en/latest/_modules/kedro_datasets/polars/eager_polars_dataset.html 

## Context
- Trying to partition a large dataframe using polars across a single column

## Steps to Reproduce
1. Sample dataset that runs locally with no issues:
```
df = pl.DataFrame(
    {"A": [1, 2, 3],
        "B": [4, 5, 6]}
)
path = "tmp/test.parquet"
df.write_parquet(
    path,
    use_pyarrow=True,
    pyarrow_options={"partition_cols": ["B"]}
)
# this also runs with no issues
df.write_parquet(
    path,
    partition_by=["B"]
)
```
2. Sample code following the same implementation:
```
# pipelines.py
from kedro.pipeline import Pipeline, node
from kedro.pipeline.modular_pipeline import pipeline
import polars as pl
def my_func():
    return pl.DataFrame(
    {"A": [1, 2, 3],
        "B": [4, 5, 6]}
    )
def create_pipeline() -> Pipeline:
    return pipeline(
    node(
                func=my_func,
                inputs={}
                outputs="my_entry",
                name="partition_polars"        
    )
```

```
# catalog.yml
# using Rust
my_entry:
  # also tried with polars.LazyPolarsDatset
  type: polars.EagerPolarsDataset 
  filepath: /tmp/test.parquet
  file_format: parquet
  save_args:
    partition_by: 
      - B
```
```
# catalog.yml
# using pyarrow (C++)
my_entry:
  type: polars.EagerPolarsDataset
  filepath: /tmp/test.parquet
  file_format: parquet
  save_args:
    use_pyarrow: True
    pyarrow_options:
      partition_cols: 
      - B
  fs_args:
    filesystem: pyarrow._fs.FileSystem
```

## Expected Result
- New partitioned parquet file should be created locally or in S3

## Actual Result

From Rust implementation:
```
DatasetError: Failed while saving data to data set
EagerPolarsDataset(file_format=parquet, filepath=/tmp/test.parquet,
load_args={}, protocol=file, save_args={'partition_by': ['dt1y']}).
'BytesIO' object cannot be converted to 'PyString'
```

From Pyarrow:
```
DatasetError: Failed while saving data to data set
 LazyPolarsDataset(filepath=/tmp/test.parquet, load_args={}, protocol=file, 
save_args={'pyarrow_options': {'compression': zstd, 'partition_cols': ['dt1y'],
'write_statistics': True}, 'use_pyarrow': True}).
Argument 'filesystem' has incorrect type (expected pyarrow._fs.FileSystem, got 
NoneType)
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.19.3
* Polars: 1.9.0 and 1.6.0
* Python version used (`python -V`): 3.11
* Operating system and version: MacOS M1 using Docker Compose + Docker Desktop

**Comment by merelcht** [comment]
Hi @alexdavis24 , I've been able to replicate the issue. I'm not super familiar with Polars and/or Pyarrow, but I think your analysis that the issue lies in the saving with BytesIO is correct. It also seems that because in the implementation of the save method, the data is written to a BytesIO buffer and then uses fsspec to write it to the target path, it completely bypasses the PyArrow filesystem and shouldn't require you to pass a filesystem argument. However, if PyArrow is being invoked with a `None` filesystem somehow, the issue might be with how fsspec or the BytesIO buffer is handled.

I managed to get things working with the following catalog entry:
```
my_entry:
  type: polars.EagerPolarsDataset
  filepath: /tmp/test.parquet
  file_format: parquet
  save_args:
    pyarrow_options:
      partition_cols:
      - B
```

So removing the explicit filesystem argument and also removing `use_pyarrow: True`. I don't know if this produces the desired result though. Let me know what you think of this.

**Comment by gitgud5000** [comment]
@merelcht  I’ve hit the same problem. Unfortunately, removing use_pyarrow: True strips out PyArrow’s faster write paths and proper partitioning support—basically defeating the whole point of specifying partition_cols.

**Comment by gitgud5000** [comment]
After exploring the internals I found a two‑part patch that restores full PyArrow + partitioning support while keeping `use_pyarrow=True` and `partition_cols=[…]`:

```python
class fixLazyPolarsDataset(LazyPolarsDataset):

    def load(self) -> pl.LazyFrame:
        load_path = str(self._get_load_path())
        if not self._exists():
            raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), load_path)

        if self._protocol == "file":
            # Local filesystem: use Polars’ built‑in scan API
            return getattr(pl, f"scan_{self._file_format}")(load_path, **self._load_args)  # type: ignore[misc]

        # Object storage: use PyArrow with explicit partitioning
        partitioning = self._load_args.pop("partitioning", None)
        if partitioning is not None:
            dataset = ds.dataset(
                load_path,
                filesystem=self._fs,
                format=self._file_format,
                partitioning=partitioning,
                **self._load_args,
            )
        else:
            dataset = ds.dataset(
                load_path,
                filesystem=self._fs,
                format=self._file_format,
                **self._load_args,
            )
        return pl.scan_pyarrow_dataset(dataset)

    def save(self, data: pl.DataFrame | pl.LazyFrame) -> None:
        save_path = get_filepath_str(self._get_save_path(), self._protocol)
        collected = data.collect() if isinstance(data, pl.LazyFrame) else data
        save_method = getattr(collected, f"write_{self._file_format}", None)
        if not save_method:
            raise DatasetError(f"Couldn't find write method for '{self._file_format}'")

        if self._save_args.get("use_pyarrow"):
            # Wrap our fsspec FS for PyArrow, then hand it to write_dataset
            pa_fs = PyFileSystem(FSSpecHandler(self._fs))
            opts = self._save_args.get("pyarrow_options", {})
            opts["filesystem"] = pa_fs
            self._save_args["pyarrow_options"] = opts
            save_method(file=save_path, **self._save_args)
        else:
            # Fallback to writing via a file handle
            with self._fs.open(save_path, **self._fs_open_args_save) as fh:
                save_method(file=fh, **self._save_args)
        self._invalidate_cache()


```

**What changed?**

1. **`save`** now wraps any fsspec‑compatible filesystem (S3, Azure, GCS, etc.) in a PyArrow [`PyFileSystem`](https://arrow.apache.org/docs/python/filesystems.html) and injects it via `pyarrow_options["filesystem"]`.
    
2. **`load`** pops out a `partitioning` argument (e.g. `"hive"`) and passes it into `pyarrow.dataset()` so that partitioned folders get correctly interpreted ([hive‑style partitioning docs](https://arrow.apache.org/docs/python/dataset.html#hive-style-partitioning)).
 
The catalog should look like this:

```yaml
trains:
  type: polars.LazyPolarsDataset
  file_format: "parquet"
  filepath: "abfs:///<....>/consolidated_full_master_table"
  credentials: azure_credentials
  load_args:
    partitioning: "hive"
  save_args:
    use_pyarrow: True
    pyarrow_options:
      partition_cols: [...]
```


I tested this on both a local filesystem and Azure Blob storage, and it resolves the error encountered by both the OP and me. A similar change should also apply to `EagerPolarsDataset`.
